# **Establishing Connection with SQL Database**
*Note: Install Pandas and SQLAlchemy if not yet installed.*

In [2]:
import pandas as pd
from sqlalchemy import create_engine, URL, text
 
url = URL.create(
    drivername="mysql+pymysql",
    username="student_ds",
    password="@studentDS#2026",
    host="vmlp.pwdlearning.cloud",
    port=3306,
    database="tokopedia"
)
engine = create_engine(url)
 
with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar()) # Connection Established = 1

1

In [5]:
# Query SQL
customer_service_tickets = pd.read_sql("SELECT * FROM customer_service_tickets", con=engine)
users = pd.read_sql("SELECT * FROM users", con=engine)
sellers = pd.read_sql("SELECT * FROM sellers", con=engine)
transactions = pd.read_sql("SELECT * FROM transactions", con=engine)
deliveries = pd.read_sql("SELECT * FROM deliveries", con=engine)

display(customer_service_tickets, users, sellers, transactions, deliveries)

,ticket_key,ticket_id,order_id,complaint_category,ticket_date,channel,resolution_status,resolution_time_hours,csat_score,agent_id
0,1,TKT-230118-9023,INV/230110/7638135,refund,2023-01-18,sosmed,resolved,8.3,2.0,AG-MDN-010
1,2,TKT-230112-8941,INV/230105/1066246,produk_rusak,2023-01-12,telepon,resolved,633.6,4.0,AG-SBY-014
2,3,TKT-240814-3460,INV/240804/3988656,lainnya,2024-08-14,telepon,resolved,0.8,NaN,AG-MKS-003
3,4,TKT-230305-3826,INV/230301/2429766,keterlambatan,2023-03-05,email,resolved,31.8,1.0,AG-BDG-002
4,5,TKT-230124-4529,INV/230101/8089124,keterlambatan,2023-01-24,sosmed,resolved,85.1,3.0,AG-SBY-010
...,...,...,...,...,...,...,...,...,...,...
31548,31549,TKT-230801-7396,INV/230725/3459945,refund,2023-08-01,sosmed,escalated,5.3,NaN,AG-SBY-012
31549,31550,TKT-241230-4067,INV/241225/7676087,keterlambatan,2024-12-30,chat,resolved,23.0,2.0,AG-SBY-016
31550,31551,TKT-230311-4296,INV/230305/4937829,kurir_kasar,2023-03-11,chat,resolved,3.0,5.0,AG-SBY-020
31551,31552,TKT-240507-4374,INV/240502/3164429,lainnya,2024-05-07,chat,resolved,4.1,4.0,AG-JKT-002
31552,31553,TKT-231102-8777,INV/231025/3451788,refund,2023-11-02,email,resolved,4.0,4.0,AG-BDG-017

,user_id,join_date,gender,location,province,age,device_type,acquisition_channel,phone_verified,email_verified,referral_code_used,account_status,last_active_date
0,222FPT2RQE,2024-12-07,Female,Surabaya,Jawa Timur,35,Android,ads,1,1,NaN,active,2024-12-09
1,222TKKG47G,2023-11-10,Female,Surabaya,Jawa Timur,46,Android,organic,1,1,NaN,active,2023-12-02
2,2242MWUZJL,2023-10-14,Female,Manado,Sulawesi Utara,41,Android,affiliate,1,0,NaN,active,2023-10-27
3,224JW2JMEQ,2024-10-05,Male,Medan,Sumatera Utara,65,Android,referral,1,1,SVHZNJ,active,2024-10-13
4,224RUVDYHV,2020-12-19,Male,DKI Jakarta,DKI Jakarta,51,Android,ads,1,1,NaN,active,2021-01-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52842,ZZW4WE4TTL,2024-11-27,Female,Surabaya,Jawa Timur,33,Android,ads,1,1,NaN,active,2024-12-04
52843,ZZWLREUL3Q,2020-09-25,Male,JAKARTA,DKI Jakarta,47,iOS,organic,1,1,NaN,active,2020-10-12
52844,ZZX6NDRML7,2024-10-21,Male,Jakarta,DKI Jakarta,56,Android,referral,1,1,7ZD7NH,active,2024-10-26
52845,ZZY9SUE2E2,2024-01-17,Female,Malang,Jawa Timur,42,iOS,organic,1,0,NaN,active,2024-02-07
52846,ZZYGF3F7HL,2021-04-20,Male,Surabaya,Jawa Timur,41,Android,ads,1,1,NaN,active,2021-04-23

,seller_id,seller_name,seller_city,seller_join_date,is_official_store,seller_rating,category_focus,avg_response_time_hours,seller_status
0,adhiarja-store-6855,Adhiarja Store,Medan,2019-10-06,0,4.10,grocery,15.3,active
1,adika-8914,Adika,Tangerang,2023-02-16,1,4.17,grocery,8.2,active
2,adinata-3700,Adinata,Yogyakarta,2019-01-04,0,5.00,elektronik,1.6,active
3,adinata-7206,Adinata,Medan,2020-02-03,0,4.76,grocery,1.1,active
4,adinata-official-5770,Adinata Official,Yogyakarta,2023-04-08,0,4.25,lainnya,8.7,active
...,...,...,...,...,...,...,...,...,...
1233,zenith-store-5713,Zenith Store,Jakarta,2024-09-06,0,4.88,lainnya,3.0,active
1234,zenith-store-shop-2094,Zenith Store Shop,Jakarta,2020-02-06,0,4.22,lainnya,14.7,active
1235,zenith-tech-official-4350,Zenith Tech Official,Jakarta,2019-06-24,0,4.13,elektronik,7.7,active
1236,zenith-wellness-official-5392,Zenith Wellness Official,Denpasar,2020-02-03,0,3.92,kesehatan,0.5,active
1237,zizi-store-2581,Zizi Store,Tangerang,2021-07-31,0,4.24,grocery,0.9,active

,transaction_key,order_id,user_id,order_date,payment_method,promo_amount,total_amount,product_category,item_quantity,seller_id,shipping_cost_charged_to_user,shipping_subsidy_platform,voucher_type,payment_channel_provider,order_status,is_campaign_period,device_used
0,1,INV/240811/8962287,LFXY4QKTAM,2024-08-11,Bank Transfer,14804,920008,lainnya,2,anggun-store-5040,8387,1581,cashback,Bank Transfer,completed,0,Android
1,2,INV/230311/4418494,TRFUZBU6U8,2023-03-11,cod,5382,366818,grocery,3,jais-mart-5341,9400,2593,cashback,COD,completed,0,Android
2,3,INV/230114/7544472,K22YYHXLTT,2023-01-14,ShopeePay,20450,412180,fashion,1,cinnamon-outfit-shop-4530,8490,2125,cashback,ShopeePay,completed,0,Android
3,4,INV/240207/1913666,TRZQBBETNL,2024-02-07,COD,0,495980,kesehatan,4,wisesa-store-1371,12891,9391,NaN,COD,returned,0,iOS
4,5,INV/231111/7533488,25HB82C54C,2023-11-11,GoPay,24830,182024,grocery,2,kalyca-mart-boutique-5885,3422,16201,diskon_persen,GoPay,completed,1,Android
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269948,269949,INV/230620/7369805,2K53UM32XW,2023-06-20,GoPay,6670,932875,perabotan,3,bianca-official-4327,8164,1077,cashback,GoPay,completed,0,Android
269949,269950,INV/240625/1332084,HQ2QTED9VA,2024-06-25,GoPay,0,620374,kesehatan,5,tenun-health-mart-2093,9432,12805,NaN,GoPay,completed,1,Web
269950,269951,INV/230811/4837818,LSF698VDDC,2023-08-11,OVO,0,112104,olahraga,2,nusantara-outfit-id-1812,21693,528,NaN,OVO,completed,0,iOS
269951,269952,INV/230325/3627689,LKTHEDHN2Y,2023-03-25,COD,0,11787283,elektronik,3,septi-gallery-4445,7851,8107,NaN,COD,completed,1,Android
269952,269953,INV/230517/8666497,RR5NMR9NTC,2023-05-17,DANA,15575,1078463,lainnya,5,ikin-grosir-7477,8347,8009,cashback,DANA,completed,0,Android

,delivery_key,order_id,courier_name,dispatch_date,delivery_date,destination_city,delivery_status,sla_promised_days,courier_service_type,shipping_zone,courier_rating
0,1,INV/230725/5419223,SiCepat,2023-07-25,2023-07-25,Malang,delivered,2,express,dalam_kota,5.0
1,2,INV/230707/2520159,GoTo Logistics,2023-07-08,2023-07-11,Padang,delivered,3,instant,luar_kota,4.7
2,3,INV/230506/9664059,JNE,2023-05-12,2023-05-22,Surabaya,returned,10,reguler,luar_pulau,4.6
3,4,INV/231220/6168058,JNE,2023-12-20,2023-12-24,JAKARTA,in_transit,3,reguler,luar_kota,NaN
4,5,INV/230212/6496572,GoTo Logistics,2023-02-13,2023-02-20,Surabaya,delivered,7,reguler,luar_pulau,4.7
...,...,...,...,...,...,...,...,...,...,...,...
261520,261521,INV/230901/2505739,GoTo Logistics,2023-09-02,2023-09-03,Denpasar,delivered,1,instant,dalam_kota,4.6
261521,261522,INV/230425/2131426,JNE,2023-04-26,2023-05-05,Balikpapan,delivered,10,reguler,luar_pulau,5.0
261522,261523,INV/230721/1650509,AnterAja,2023-07-21,2023-07-29,Denpasar,delivered,8,express,luar_pulau,NaN
261523,261524,INV/231125/5499253,JNE,2023-11-25,2023-11-29,Jakarta,delivered,5,same_day,luar_pulau,4.3
261524,261525,INV/230213/8443516,AnterAja,2023-02-13,2023-03-08,Surabaya,delivered,9,reguler,luar_pulau,2.2

In [6]:
customer_service_tickets.to_csv("customer_service_tickets.csv", index=False)
users.to_csv("users.csv", index=False)
sellers.to_csv("sellers.csv", index=False)
transactions.to_csv("transactions.csv", index=False)
deliveries.to_csv("deliveries.csv", index=False)